### ISSUE TITLE
Blockhound doesn't detect the blocking call in my environment (Java 13 on windows)

### ISSUE THREAD

**Issue by theonlyguills** [dsibilio/blockhound-demo#1]
Running the `blockingInNonBlockingThreadsShouldNotBeAllowed` test on my system does not detect the blocking call. I also confirmed this by changing the code to

```
    @Test
    void blockingInNonBlockingThreadsShouldNotBeAllowed() {
        StepVerifier
        .create(underTest.blockingIsNotAllowed())
        .expectNext(1)
        .expectComplete()
        .verify();
    }
```

and this test passes. I confirmed that `BlockHound.install()` is getting called by the listener.

What else can I check ?

**Comment by bsideup** [comment]
Java 13? See https://github.com/reactor/BlockHound/issues/33

**Comment by theonlyguills** [comment]
That was fast. I get the same behavior described in that bug on windows and oracle jdk 13.0.1.

Without the flag nothing happens. I added the flag and it seems to work as described.

Something to note though, it gives this warning:
`Java HotSpot(TM) 64-Bit Server VM warning: Option AllowRedefinitionToAddDeleteMethods was deprecated in version 13.0 and will likely be removed in a future release.`

We might need to find another workaround soon.

**Comment by bsideup** [comment]
Ha! I didn't notice that you just submitted the issue 😅 

Yes, we're aware of the deprecation and are thinking about possible solutions to workaround it. Unfortunately there was a behaviour change in OpenJDK and it broke the way BlockHound works, so we will need to find another one.
Consider subscribing to the issue to stay updated about the progress.

**Comment by dsibilio** [comment]
Thank you @theonlyguills for the precious feedback and @bsideup for providing the workaround in record time 😄

I'm closing this issue as this demo project was written for Java 8 and should be run with the same version, further progress towards potential different solutions for this issue can be found at https://github.com/reactor/BlockHound/issues/33, as mentioned by @bsideup.
